name: sync master + merge main
on:
  schedule:
    - cron: '12 0-15/3 * * *'
  workflow_dispatch:
jobs:
  merge-branch:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: sync LXK9301-jd_scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/LXK9301/jd_scripts.git"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}

      - name: Merge master to main
        uses: devmasx/merge-branch@v1.3.1	
        if: env.PAT	
        with:	
          type: now	
          from_branch: master	
          target_branch: main	
          github_token: ${{ secrets.PAT }}
